name: verify

on:
  schedule:
    - cron: "0/30 * * * *"

permissions:
  id-token: write
  contents: read

jobs:
  verify:
    runs-on:  ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run script
      run: |
        pip install ics
        python3 verify_feeds.py --end "${{ vars.END_DATE}}" "${{ secrets.WHITBY_BOOKINGCOM }}" "${{ secrets.WHITBY_AIRBNB }}"
      working-directory: ./python
      
